import { Box, Divider, Flex, IconButton } from "@chakra-ui/react";
import Head from "next/head";
import React, { useState } from "react";
import "@fontsource/heebo";
import Link from "next/link";
import { Icon, HamburgerIcon, CloseIcon } from "@chakra-ui/icons";
import OpenMenu from "./OpenMenu";
import Navbar from "./Navbar";

const Header = () => {
  return (
    <Box
      fontFamily="Heebo"
      fontStyle="normal"
      fontWeight="500"
      fontSize="20px"
      width="100vw"
      maxWidth="full"
      lineHeight="29px"
      height={{ lg: "100px", base: "3.125rem" }}
    >
      <Head>
        <title>Portfolio UI - Web & Mobile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        position="fixed"
        top="0"
        overflow="hidden"
        width="inherit"
        height={{ lg: "3.125rem", base: "3.125rem" }}
        display="block"
        background="white"
        zIndex={1}
        pr={5}
      >
        <Navbar />
      </Box>
    </Box>
  );
};

export default Header;
